CREATE TABLE IF NOT EXISTS piece_service.unit
(
    code  VARCHAR(10)  NOT NULL,
    name  VARCHAR(100) NOT NULL,
    index INT          NOT NULL,
    PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS piece_service.problem
(
    problem_id BIGINT         NOT NULL,
    unit_code  VARCHAR(10)    NOT NULL,
    level      INT            NOT NULL,
    type       VARCHAR(20)    NOT NULL,
    contents   VARCHAR(10000) NOT NULL,
    answer     VARCHAR(20)    NOT NULL,
    PRIMARY KEY (problem_id),
    CONSTRAINT FK_PROBLEM_ON_UNIT_CODE FOREIGN KEY (unit_code) REFERENCES unit (code)
);

CREATE TABLE IF NOT EXISTS piece_service.piece
(
    piece_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP                               NOT NULL,
    last_modified_at    TIMESTAMP                               NOT NULL,
    name                VARCHAR(50)                             NOT NULL,
    maker_id            BINARY(16)                              NOT NULL,
    total_student_count INT                                     NOT NULL,
    total_problem_count INT                                     NOT NULL,
    PRIMARY KEY (piece_id)
);

CREATE TABLE IF NOT EXISTS piece_service.piece_problem
(
    piece_problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP                               NOT NULL,
    last_modified_at TIMESTAMP                               NOT NULL,
    piece_id         BIGINT                                  NOT NULL,
    problem_id       BIGINT                                  NOT NULL,
    number           INT                                     NOT NULL,
    PRIMARY KEY (piece_problem_id),
    CONSTRAINT FK_PIECEPROBLEM_ON_PIECE FOREIGN KEY (piece_id) REFERENCES piece (piece_id),
    CONSTRAINT FK_PIECEPROBLEM_ON_PROBLEM FOREIGN KEY (problem_id) REFERENCES problem (problem_id)
);

CREATE TABLE IF NOT EXISTS piece_service.student_piece
(
    student_piece_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP                               NOT NULL,
    last_modified_at TIMESTAMP                               NOT NULL,
    student_id       BINARY(16)                              NOT NULL,
    piece_id         BIGINT                                  NOT NULL,
    PRIMARY KEY (student_piece_id),
    CONSTRAINT FK_STUDENTPIECE_ON_PIECE FOREIGN KEY (piece_id) REFERENCES piece (piece_id)
);

CREATE TABLE IF NOT EXISTS piece_service.piece_stat
(
    piece_id                BIGINT    NOT NULL,
    created_at              TIMESTAMP NOT NULL,
    last_modified_at        TIMESTAMP NOT NULL,
    student_stats_container BLOB      NOT NULL,
    problem_stats_container BLOB      NOT NULL,
    PRIMARY KEY (piece_id),
    CONSTRAINT FK_PIECE_STAT_ON_PIECE FOREIGN KEY (piece_id) REFERENCES piece (piece_id)
);

CREATE INDEX IF NOT EXISTS idx_problem_unit_code_level_type
    ON piece_service.problem (unit_code, level, type);